import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

// All entries from the Vyral creator application Google Sheet (read 2026-08-04)
const SHEET_DATA = [
  { firstName: "Klara", lastName: "Ralevic", email: "klara@gmail.com", over18: true, location: "Asia", tiktok: "https://tiktok.com/", instagram: "janskj", notes: "shameless_pets, meetciao, getminds", submittedAt: "2026-03-04T18:42:32.232Z" },
  { firstName: "mackenzie", lastName: "page", email: "kalaharmackenzie@gmail.com", over18: true, location: "US", tiktok: "mackenzie_kate_teaches", instagram: "mackenzie_kate_teaches", notes: "all", submittedAt: "2026-03-04T19:22:26.199Z" },
  { firstName: "Sam", lastName: "James", email: "samjames.flp@gmail.com", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@samjames.de", instagram: "https://www.instagram.com/samjames.de/", notes: "natively, artie, getminds, meetciao", submittedAt: "2026-03-09T18:00:43.754Z" },
  { firstName: "Sonja", lastName: "Buschbacher", email: "sonja.buschbacher97@gmail.com", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@travel.sonja", instagram: "https://www.instagram.com/travel.sonja/", notes: null, submittedAt: "2026-03-11T13:06:20.220Z" },
  { firstName: "Ebba", lastName: "Klingvall", email: "klingvall.ebba@gmail.com", over18: true, location: "Europe", tiktok: "www.tiktok.com/@ebbsoul4", instagram: "https://www.instagram.com/ebbakl1ngvall", notes: null, submittedAt: "2026-03-15T12:55:51.851Z" },
  { firstName: "Alina", lastName: "Schiffmann", email: "alina.schiffmann@gmx.net", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@alinaa_05_", instagram: "https://www.instagram.com/alinaa.9381", notes: null, submittedAt: "2026-03-16T08:01:03.803Z" },
  { firstName: "Isabel", lastName: "van den Brink", email: "isabelvandenbrink123@gmail.com", over18: true, location: "Europe", tiktok: "isabelthrifts", instagram: "isabel.mindsai", notes: null, submittedAt: "2026-03-16T18:02:53.252Z" },
  { firstName: "Firas", lastName: "Hussin", email: "fhussin9609@gmail.com", over18: true, location: "Canada", tiktok: "https://www.tiktok.com/@firasstudies", instagram: "https://www.instagram.com/firasstudies", notes: null, submittedAt: "2026-03-17T03:06:26.148Z" },
  { firstName: "Rayan", lastName: "Bhaila", email: "rayanbhaila@gmail.com", over18: true, location: "Canada", tiktok: "https://www.tiktok.com/@rayan.locked", instagram: "https://www.instagram.com/rayan.locked", notes: null, submittedAt: "2026-03-17T03:07:48.634Z" },
  { firstName: "Eric", lastName: "Xie", email: "ericxie.hz@gmail.com", over18: true, location: "Canada", tiktok: "tiktok.com/@ericviews", instagram: "https://instagram.com/eric.views", notes: null, submittedAt: "2026-03-17T03:30:27.030Z" },
  { firstName: "sukhjit", lastName: "singh", email: "sukhjitsingh0976@gmail.com", over18: true, location: "US", tiktok: "https://sjugcprofolio.my.canva.site", instagram: "https://sjugcprofolio.my.canva.site", notes: null, submittedAt: "2026-03-17T03:46:50.850Z" },
  { firstName: "Ferdinand", lastName: "Seizmair", email: "fseizmair45@gmail.com", over18: true, location: "Europe", tiktok: "www.tiktok.com/@frnnd462", instagram: "https://www.instagram.com/ferdinandjds", notes: null, submittedAt: "2026-03-17T11:04:53.953Z" },
  { firstName: "Kevin", lastName: "Bui", email: "bykevinbui@gmail.com", over18: true, location: "Canada", tiktok: "https://www.tiktok.com/@kevin.ugc", instagram: "https://www.instagram.com/kevin.bui/", notes: null, submittedAt: "2026-03-17T17:35:52.852Z" },
  { firstName: "Mubeen", lastName: "Bhatti", email: "freelancemubeenbussiness@gmail.com", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@freelancemubeen", instagram: "https://www.instagram.com/freelancemubeen/", notes: null, submittedAt: "2026-03-17T18:29:32.332Z" },
  { firstName: "Kamil", lastName: "Gulman", email: "kamilgulman.05@gmail.com", over18: true, location: "Canada", tiktok: "https://www.tiktok.com/@kamil.gulman", instagram: "https://www.instagram.com/kamlinzz/", notes: null, submittedAt: "2026-03-18T03:42:35.435Z" },
  { firstName: "Tibet", lastName: "Yeserenyuva", email: "yeserenyuvatibet@gmail.com", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@tibet.ycreate", instagram: "https://www.instagram.com/tibsyecreate.mp4", notes: null, submittedAt: "2026-03-18T09:40:09.009Z" },
  { firstName: "Edwin Ray", lastName: "Sanchez", email: "edwinraybiz@gmail.com", over18: true, location: "US", tiktok: "https://www.tiktok.com/@edwinray", instagram: "https://www.instagram.com/edwinray_", notes: null, submittedAt: "2026-03-18T17:08:50.850Z" },
  { firstName: "Enzo", lastName: "Silvestre", email: "enzojoaquin.silvestre@gmail.com", over18: true, location: "Philippines", tiktok: "https://www.tiktok.com/@itswakini1", instagram: "https://www.instagram.com/itswakini", notes: null, submittedAt: "2026-03-19T03:41:19.019Z" },
  { firstName: "Dustin", lastName: "Jones", email: "DustinLeeJones100@gmail.com", over18: true, location: "US", tiktok: "https://www.tiktok.com/@studyingwithdustin", instagram: "https://www.instagram.com/studyingwithdustin", notes: null, submittedAt: "2026-03-20T14:53:48.059Z" },
  { firstName: "Dakota", lastName: "Jones", email: "dakjon22@gmail.com", over18: true, location: "US", tiktok: "www.tiktok.com/@datboydakk", instagram: "https://www.instagram.com/dakotajones._", notes: null, submittedAt: "2026-03-20T14:55:21.499Z" },
  { firstName: "Sean", lastName: "Hunsicker", email: "seanhunsicker8@gmail.com", over18: true, location: "US", tiktok: "https://www.tiktok.com/@seanhunsi", instagram: null, notes: null, submittedAt: "2026-03-20T15:45:19.519Z" },
  { firstName: "Dean", lastName: "Hunsicker", email: "deanhunsicker@gmail.com", over18: true, location: "US", tiktok: "https://www.tiktok.com/@drewcollinnss", instagram: "https://www.instagram.com/drewcollinnss", notes: null, submittedAt: "2026-03-23T15:35:46.246Z" },
  { firstName: "Ryan", lastName: "Thomas", email: "ryanthomasbco@gmail.com", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@notryanvee", instagram: "https://www.instagram.com/ryanthomas.jpeg", notes: null, submittedAt: "2026-03-24T00:42:03.003Z" },
  { firstName: "Jayc", lastName: "Satoshi", email: "ugcwithjayc@gmail.com", over18: false, location: "Canada", tiktok: "https://www.tiktok.com/@fitnesswithjayc", instagram: "https://www.instagram.com/fitnesswithjayc/", notes: null, submittedAt: "2026-03-24T16:55:34.959Z" },
  { firstName: "Mia", lastName: "de Boer", email: "mia.de.boer@gmx.de", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@your.favorite.ginger.1", instagram: "https://www.instagram.com/mia.ldbr", notes: null, submittedAt: "2026-03-25T09:59:58.897Z" },
  { firstName: "Alejandro", lastName: "McCowen", email: "alejandrom.creator@gmail.com", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@alejandromccowen", instagram: "https://www.instagram.com/alejandromccowen/", notes: null, submittedAt: "2026-03-29T14:26:39.239Z" },
  { firstName: "Gideon", lastName: "Jansen", email: "gideonjansen17@gmail.com", over18: true, location: "Canada", tiktok: "https://www.tiktok.com/@gideonnn.j", instagram: "instagram.com/gideon_jansen_/", notes: null, submittedAt: "2026-03-29T04:16:49.749Z" },
  { firstName: "Zachary", lastName: "De Guzman", email: "zacharydg13@gmail.com", over18: true, location: "Canada", tiktok: "http://www.tiktok.com/@z.puralaxy", instagram: "https://www.instagram.com/historicbanana/", notes: null, submittedAt: "2026-03-31T17:03:07.007Z" },
  { firstName: "Mariana", lastName: "Hurtado", email: "marihurcar02@gmail.com", over18: true, location: "Europe", tiktok: "Marihurcar02", instagram: "Marihurcar", notes: null, submittedAt: "2026-04-06T12:44:03.274Z" },
  { firstName: "Luisa", lastName: "Quirmbach", email: "luisaquirmbach@yahoo.de", over18: true, location: "Europe", tiktok: "https://www.instagram.com/curlyfulloftravel/", instagram: "https://www.instagram.com/curlyfulloftravel/", notes: null, submittedAt: "2026-04-07T09:34:58.930Z" },
  { firstName: "Sofia", lastName: "Fernandes", email: "sofiabusiness86@gmail.com", over18: true, location: "Europe", tiktok: "https://tiktok.com/@sofiafnd_", instagram: "https://instagram.com/sofiafnd_", notes: null, submittedAt: "2026-04-07T18:38:51.387Z" },
  { firstName: "Olivia", lastName: "Rajabiun", email: "oliviarajabiun@gmail.com", over18: true, location: "US", tiktok: "wearsliv", instagram: "oliviarajabiun", notes: null, submittedAt: "2026-04-08T08:52:03.808Z" },
  { firstName: "Vanessa", lastName: "Ribeiro Martins", email: "04martins.vanessa@gmail.com", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@vanessa.rxmm", instagram: "https://www.instagram.com/vanessa.rxm", notes: null, submittedAt: "2026-04-10T11:33:32.332Z" },
  { firstName: "Melia", lastName: "Subra", email: "melia.subra@gmail.com", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@meldailycreates", instagram: "https://www.instagram.com/meliaa.sbr", notes: null, submittedAt: "2026-04-20T14:10:45.969Z" },
  { firstName: "Marbella", lastName: "Rojas", email: "bellaagency593@gmail.com", over18: true, location: "US", tiktok: "Marbellarojasss", instagram: "Marbellarojass", notes: null, submittedAt: "2026-04-14T03:23:23.580Z" },
  { firstName: "Sree Nikitha Reddy", lastName: "Doddareddy", email: "sreenikithareddyd@gmail.com", over18: true, location: "US", tiktok: "None", instagram: "https://www.instagram.com/sree_nikitha_reddy", notes: null, submittedAt: "2026-04-14T13:58:12.998Z" },
  { firstName: "Priyal", lastName: "Kala", email: "priyalkala2002@gmail.com", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@priyal.kala", instagram: "https://www.instagram.com/priyal__kala", notes: null, submittedAt: "2026-04-14T16:21:14.580Z" },
  { firstName: "Sonja", lastName: "Buschbacher", email: "travel.sonja.inquiries@gmail.com", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@travel.sonja", instagram: "https://www.instagram.com/travel.sonja/", notes: null, submittedAt: "2026-04-14T17:55:37.979Z" },
  { firstName: "Danielle", lastName: "Poremba", email: "danielleugc92@gmail.com", over18: true, location: "Canada", tiktok: "https://www.tiktok.com/@danielleugc92", instagram: "https://www.instagram.com/danielleugc.92", notes: "Referral: Alyssa Mason", submittedAt: "2026-04-23T11:49:45.898Z" },
  { firstName: "Tanja", lastName: "van den Brink", email: "tanja-tanja@live.nl", over18: true, location: "Europe", tiktok: "https://tiktok.com/@tanvdb1", instagram: "https://www.instagram.com/tanvdbrink", notes: "newly.app referral. Isabel van den Brink is my niece.", submittedAt: "2026-04-23T14:17:48.848Z" },
  { firstName: "Bobby", lastName: "Amonitti", email: "amonitti.bobby@yahoo.com", over18: true, location: "US", tiktok: "www.tiktok.com/@justchillinu", instagram: "https://www.instagram.com/bobbyamonitti", notes: null, submittedAt: "2026-04-23T18:33:33.534Z" },
  { firstName: "Gem", lastName: "Doctolero", email: "genesisgemd@gmail.com", over18: true, location: "Canada", tiktok: "https://www.tiktok.com/@gdoctolero", instagram: "https://www.instagram.com/gdoctolero/", notes: "Nurse and content creator based in Toronto. Lifestyle, wellness, travel, beauty.", submittedAt: "2026-05-01T18:30:33.325Z" },
  { firstName: "Nynke", lastName: "Herik", email: "nynkeherik@gmail.com", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@nynke_herik", instagram: "https://www.instagram.com/nynke_herik", notes: "Ambassador at Anara. Experience as teamlead/ambassador at Retro.", submittedAt: "2026-05-10T15:12:50.050Z" },
  { firstName: "Mathilda", lastName: "van der Post", email: "mathi@vanderpost.de", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@mavdti", instagram: "https://www.instagram.com/mavdti/", notes: "Referred by Mia", submittedAt: "2026-05-10T12:32:54.655Z" },
  { firstName: "Carlo", lastName: "Gamalero", email: "gamalerocarlo@gmail.com", over18: true, location: "Europe", tiktok: null, instagram: "https://www.instagram.com/carlo_gamalero/", notes: "24 yr old French-Italian actor from Barcelona. Speaks 5 languages.", submittedAt: "2026-05-13T13:49:18.518Z" },
  { firstName: "Erik", lastName: "Xhaci", email: "ugcwithsamba@gmail.com", over18: true, location: "Canada", tiktok: "https://www.tiktok.com/@vsambaa", instagram: "https://www.instagram.com/vsambaa/", notes: "Clean, engaging content that converts well.", submittedAt: "2026-05-13T23:33:01.045Z" },
  { firstName: "Chiara", lastName: "Rossini", email: "rossini.chiara20@gmail.com", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@_chiaross", instagram: "https://www.instagram.com/_chiaross", notes: null, submittedAt: "2026-05-14T12:22:41.135Z" },
  { firstName: "Ginevra", lastName: "Scaramucci", email: "ginevra.scaramucci@gmail.com", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@rumplestiltskinnn", instagram: null, notes: null, submittedAt: "2026-05-14T12:23:03.101Z" },
  { firstName: "Carolina", lastName: "Bugaj", email: "carolinabugaj1@gmail.com", over18: true, location: "Europe", tiktok: "https://tiktok.com/@caro.bgj", instagram: "https://instagram.com/carolinabgj", notes: "Manages university social media. Street interviews, trends, local collaborations.", submittedAt: "2026-05-14T12:39:09.609Z" },
  { firstName: "Enrico", lastName: "Lima", email: "enricoemail02@gmail.com", over18: true, location: "Europe", tiktok: "@enricolima42", instagram: "Enrico.lima_", notes: null, submittedAt: "2026-05-14T12:57:57.957Z" },
  { firstName: "Mr", lastName: "Master", email: "funmaster377@gmail.com", over18: true, location: "US", tiktok: "https://www.tiktok.com/@mr.master.poly", instagram: "https://www.instagram.com/mr.master.poly/", notes: null, submittedAt: "2026-05-17T18:19:48.048Z" },
  { firstName: "Micael", lastName: "Lariccia", email: "Micael.Lariccia@gmail.com", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@mikemetallaro", instagram: "https://www.instagram.com/mikemetallaro/", notes: "DJ, music-related content.", submittedAt: "2026-05-18T10:02:15.515Z" },
  { firstName: "Camilla", lastName: "Gianantonio", email: "gianantonio.cami@icloud.com", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@camillagianantonioo", instagram: "https://www.instagram.com/camillagianantonio", notes: "Vincent/Ecosia referral", submittedAt: "2026-05-18T10:10:03.803Z" },
  { firstName: "Beatrice", lastName: "Bos", email: "bosbeatrice5@gmail.com", over18: true, location: "Europe", tiktok: null, instagram: "beatrice.bos.o6", notes: "Climate activist. Made content for the movement.", submittedAt: "2026-05-18T10:12:18.240Z" },
  { firstName: "Alice", lastName: "Hu", email: "geniojx@gmail.com", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@allunaemezza", instagram: "https://www.instagram.com/mezza_lhuna", notes: "Vincent/Ecosia referral", submittedAt: "2026-05-18T10:39:18.018Z" },
  { firstName: "Frida", lastName: "Coello", email: "fridacoello03@gmail.com", over18: true, location: "US", tiktok: "fridacoello2", instagram: "frida.36254", notes: "UGC beginner, started Nov 2025. Got serious 2 years ago.", submittedAt: "2026-05-18T19:32:42.842Z" },
  { firstName: "Raf", lastName: "Adnan", email: "UGC.raf.ugc@gmail.com", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@ugc_raf_", instagram: "https://www.instagram.com/ugc_raf/reels/", notes: "From the UK", submittedAt: "2026-05-19T14:02:53.253Z" },
  { firstName: "Alex", lastName: "Chase", email: "acbusiness324@gmail.com", over18: true, location: "US", tiktok: "dealsfromac", instagram: "itsalexchase", notes: "Referred by Anthony Chase (brother)", submittedAt: "2026-05-21T17:52:58.858Z" },
  { firstName: "Ana", lastName: "Morais", email: "ugc.anamorais@gmail.com", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@anamorais.ugc", instagram: "https://www.instagram.com/ugcanamorais", notes: "210k+ views in first 3 weeks on one campaign.", submittedAt: "2026-05-24T07:11:13.714Z" },
  { firstName: "Hannah", lastName: "Schindler", email: "schindha17@gmail.com", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@hanilixa", instagram: "https://www.instagram.com/hanilixa", notes: "Previously a creator (@hannahthriftss)", submittedAt: "2026-05-25T11:54:24.424Z" },
  { firstName: "Chiara Dida", lastName: "Cigolini", email: "chiara05.home@gmail.com", over18: true, location: "Europe", tiktok: "chiaracigolini", instagram: "chiaracigolini", notes: "Vincent/Ecosia referral", submittedAt: "2026-05-27T15:42:30.430Z" },
  { firstName: "Diana", lastName: "Burroni", email: "a.dburroni@gmail.com", over18: true, location: "Europe", tiktok: null, instagram: "https://www.instagram.com/dburroni", notes: "Vincent/Ecosia referral. Speaks Italian and English. No public TikTok.", submittedAt: "2026-05-27T15:42:38.038Z" },
  { firstName: "Vishaal", lastName: "Ananthapadmanaban Vijay", email: "vishaalav2001@gmail.com", over18: true, location: "Europe", tiktok: "vishaalav8", instagram: "https://www.instagram.com/vishaal_av", notes: null, submittedAt: "2026-05-28T09:21:49.249Z" },
  { firstName: "Bernardo", lastName: "Marchana", email: "bernardomarchana@hotmail.com", over18: true, location: "Europe", tiktok: null, instagram: "https://www.instagram.com/marchana21", notes: "Vincent/Ecosia referral", submittedAt: "2026-05-28T11:20:26.226Z" },
  { firstName: "Ayushi", lastName: "Acharya", email: "hello@ayushiacharya.com", over18: true, location: "Europe", tiktok: null, instagram: "https://www.instagram.com/bhooki.banjaran/", notes: null, submittedAt: "2026-05-28T12:17:39.039Z" },
  { firstName: "Sarah", lastName: "Krause", email: "sarahkrause1603@gmail.com", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@tumblrsaraah", instagram: "https://www.instagram.com/tumblrsaarah", notes: "2+ years UGC experience. Authentic storytelling.", submittedAt: "2026-05-29T10:32:13.312Z" },
  { firstName: "Lisa", lastName: "Sokolska", email: "lisasokolska@gmail.com", over18: true, location: "Europe", tiktok: "masterzeugsss", instagram: "llisaasl", notes: "From Berlin. 1 year UGC experience.", submittedAt: "2026-05-30T14:19:51.951Z" },
  { firstName: "Maya", lastName: "Falah", email: "mayaelizabethfalah@gmail.com", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@maya.elizabeth6", instagram: "https://www.instagram.com/mayaefalah", notes: "Background at Deloitte. Currently content creator at studyagent.ai.", submittedAt: "2026-06-01T10:11:03.503Z" },
  { firstName: "Caitlin", lastName: "Strate", email: "caitlinstrate@gmail.com", over18: true, location: "US", tiktok: "https://www.tiktok.com/caitlinstrate", instagram: "https://www.instagram.com/caitlinstrate", notes: null, submittedAt: "2026-06-04T12:34:35.916Z" },
  { firstName: "Mohammad", lastName: "Bshr", email: "ecommo27@gmail.com", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@ecomoh", instagram: "Ecommo", notes: "Runs own e-commerce brands. Germany-based. Looking for UGC side work.", submittedAt: "2026-06-06T21:36:47.247Z" },
  { firstName: "Wiktoria", lastName: "Fratczak", email: "wiki2080@proton.me", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@wikiheals", instagram: "https://www.instagram.com/wikihealingjourney/reels/", notes: "Worked on one of Vyral's campaigns before.", submittedAt: "2026-06-15T23:23:27.414Z" },
  { firstName: "Marzia", lastName: "Amendolia", email: "marziaamendolia03@gmail.com", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@marziaamendolia3", instagram: null, notes: "Italian native speaker. Referred by Emma Rigliano, spoke with Klara.", submittedAt: "2026-06-16T20:52:29.529Z" },
  { firstName: "disha", lastName: "lokwani", email: "workwithdishalokwani@gmail.com", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@dlokwani", instagram: "https://www.instagram.com/disha_lokwani/", notes: null, submittedAt: "2026-06-17T08:45:23.523Z" },
  { firstName: "Lucia", lastName: "Jenkins", email: "Jenkins.ggd@gmail.com", over18: true, location: "Europe", tiktok: "https:/www.tiktok.com/@frecklefacee", instagram: "https://www.instagram.com/luciajenkins7/", notes: "@Brokefounder reached out through TikTok about Ecosia.", submittedAt: "2026-06-17T14:44:13.373Z" },
  { firstName: "Jasmine", lastName: "Monrouxe", email: "ugcbyjasmine.108@gmail.com", over18: true, location: "Australia", tiktok: "TikTok.com/@ugcbyjasminemay", instagram: "Instagram.com/ugcbyjasminemay", notes: "Worked with Vyral Labs on the Juno campaign.", submittedAt: "2026-06-18T23:20:42.700Z" },
  { firstName: "Claire", lastName: "Beishon", email: "clairebeishon@gmail.com", over18: true, location: "UK", tiktok: "https://www.tiktok.com/@beishon_", instagram: "https://www.instagram.com/beishon", notes: null, submittedAt: "2026-06-22T09:33:22.922Z" },
  { firstName: "Julius", lastName: "Kirchner", email: "julius.kirchner@code.berlin", over18: true, location: "Europe", tiktok: "milkboy.nl", instagram: "https://www.instagram.com/julius.krn/", notes: "Would love to get to know the opportunities in this space.", submittedAt: "2026-06-22T12:53:22.922Z" },
  { firstName: "German", lastName: "Lozano", email: "germanlozano99@gmail.com", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@germanlozano11", instagram: "https://www.instagram.com/germanlozano11/", notes: null, submittedAt: "2026-06-23T10:26:27.727Z" },
  { firstName: "Avani", lastName: "Apte", email: "avani.n.apte@gmail.com", over18: true, location: "US", tiktok: "https://tiktok.com/@avanisreels", instagram: "https://www.instagram.com/avanireels/", notes: null, submittedAt: "2026-06-24T07:11:57.957Z" },
  { firstName: "Maria Ilenia", lastName: "Destito", email: "mariailenia.destito@gmail.com", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@mariailenia35", instagram: "https://www.instagram.com/sonomarle", notes: "UGC Creator based in Italy. Authentic storytelling.", submittedAt: "2026-06-24T15:36:09.609Z" },
  { firstName: "Deanna", lastName: "Cai", email: "deannamae.business@gmail.com", over18: true, location: "Philippines", tiktok: "deya_mae", instagram: "https://www.instagram.com/tianmeistudies", notes: "Can do canvas UGC, posting every day.", submittedAt: "2026-06-27T15:35:51.515Z" },
  { firstName: "Mia", lastName: "de Boer", email: "mia.de.boer@gmx.de", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@your.favorite.ginger.1", instagram: "https://www.instagram.com/mia.ldbr", notes: "4 months UGC exp. Worked with Faircado, Getminds.ai.", submittedAt: "2026-06-29T06:59:39.039Z" },
  { firstName: "Poppy", lastName: "Kemball", email: "kemballpoppy@gmail.com", over18: true, location: "Europe", tiktok: "@poppy.thrifts", instagram: "@poppy.thrifting", notes: "Was in the Faircado program.", submittedAt: "2026-06-29T07:05:48.848Z" },
  { firstName: "Victoria", lastName: "Iglesias", email: "victoria.iglesias9@gmail.com", over18: true, location: "Europe", tiktok: "victoriaiglesiasri", instagram: "victoriiaiglesias", notes: "Content creator for Faircado.", submittedAt: "2026-06-29T08:39:00.000Z" },
  { firstName: "Isabel", lastName: "van den Brink", email: "isabelvandenbrink123@gmail.com", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@isabellearnsgerman", instagram: "https://www.instagram.com/isabel.learnsgerman", notes: "Love working with you!", submittedAt: "2026-06-29T10:41:00.000Z" },
  { firstName: "Mame Khady", lastName: "Seye", email: "mimaseye18@gmail.com", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@mimasworld19", instagram: "https://www.instagram.com/mima12334", notes: "Faircado ambassador for ~1 year. Loves fashion content.", submittedAt: "2026-06-29T12:42:03.003Z" },
  { firstName: "Linnea", lastName: "Hennig", email: "linnea.hennig@t-online.de", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@linnealuisa", instagram: "https://www.instagram.com/linneathrifts", notes: "Faircado creator for almost 1 year. 2 videos/day. Adapted English scripts to German.", submittedAt: "2026-06-29T18:48:04.004Z" },
  { firstName: "Eugenia", lastName: "Robe", email: "robeeugenia@gmail.com", over18: true, location: "Europe", tiktok: "https://vm.tiktok.com/ZNRw9nR2x/", instagram: "https://www.instagram.com/eugeniar0be", notes: "Worked with Ecosia through Viral Labs. Great experience.", submittedAt: "2026-06-29T19:19:28.228Z" },
  { firstName: "Verena", lastName: "Kadegge", email: "k.verena2@web.de", over18: true, location: "Europe", tiktok: "www.tiktok.com/@verenaena_", instagram: "https://www.instagram.com/verenaena_", notes: "Faircado creator. Fashion, UGC, beauty.", submittedAt: "2026-06-29T20:08:37.037Z" },
  { firstName: "Polina", lastName: "Bayntun", email: "pollybayntun@gmail.com", over18: true, location: "Europe", tiktok: "pbayntun", instagram: "bayntunpolly", notes: "UGC for Faircado, MeetCiao, Pickem. Currently: Artie and Ecosia.", submittedAt: "2026-06-30T11:20:40.040Z" },
  { firstName: "hanna", lastName: "strough", email: "hannastrough@gmail.com", over18: true, location: "US", tiktok: "hannamstrough", instagram: "hannamstrough", notes: null, submittedAt: "2026-06-30T20:06:25.025Z" },
  { firstName: "Stella", lastName: "Gordon", email: "stella.marie.gordon@gmail.com", over18: true, location: "Europe", tiktok: "stella.icema", instagram: "stella.icema", notes: "1 year for Faircado before program ended.", submittedAt: "2026-07-05T12:01:08.008Z" },
  { firstName: "Jaxon", lastName: "Villanueva", email: "mishterj246@gmail.com", over18: false, location: "Canada", tiktok: "https://www.tiktok.com/@mediabymishter", instagram: "https://www.instagram.com/mediabymishter/", notes: "Portfolio: https://canva.link/oyaa5d2dr94ol1e", submittedAt: "2026-07-15T07:17:36.636Z" },
  { firstName: "Aarnav", lastName: "Jain", email: "aarnavjain18@gmail.com", over18: true, location: "Canada", tiktok: "https://tiktok.com/@aarnaaav", instagram: "https://instagram.com/irlaarnav", notes: "Referred by Mohammed. Portfolio: https://aarnavsugcportfolio.netlify.app", submittedAt: "2026-07-17T17:44:28.428Z" },
  { firstName: "Vanessa", lastName: "Romeo", email: "vany98@tiscali.it", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@vanessar98", instagram: null, notes: "UGC creator for her company. TikTok only, no Instagram.", submittedAt: "2026-07-18T17:19:21.921Z" },
  { firstName: "Yen-Ting", lastName: "Chen", email: "tingmakesmoves@gmail.com", over18: true, location: "Australia", tiktok: "https://www.tiktok.com/@tingmakesmoves_", instagram: "https://www.instagram.com/tingmakesmoves/", notes: "Portfolio: https://tingdoesugc.my.canva.site/", submittedAt: "2026-07-24T04:27:08.408Z" },
  { firstName: "Sven", lastName: "Oechler", email: "svenmoritz99sge@gmail.com", over18: true, location: "Europe", tiktok: "https://tiktok.com/@sven.frontpage", instagram: "https://instagram.com/svenoechler", notes: null, submittedAt: "2026-07-24T14:18:25.225Z" },
  { firstName: "Evelin", lastName: "Martin", email: "mynameisevelinx@gmail.com", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@evelinxmartin", instagram: "https://instagram.com/evelinxmartin", notes: null, submittedAt: "2026-07-27T09:53:47.747Z" },
  { firstName: "Paige", lastName: "Eligon", email: "profitswithpaige@hotmail.com", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@profitswithpaigee", instagram: "https://www.instagram.com/profitswithpaigee", notes: "Referred by Ana Morais. Portfolio: https://canva.link/ngnczf4jzhnple0", submittedAt: "2026-07-31T05:21:33.533Z" },
  { firstName: "Nefeli", lastName: "Konstantinidou", email: "nefeliknd@gmail.com", over18: true, location: "Europe", tiktok: "www.tiktok.com/@nefeliknd", instagram: "https://www.instagram.com/nefeliknd/", notes: null, submittedAt: "2026-08-02T07:17:02.702Z" },
  { firstName: "Laura", lastName: "Pasler", email: "businessmitlaura@gmail.com", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@lay1706", instagram: "https://www.instagram.com/lay1706", notes: null, submittedAt: "2026-08-01T14:32:26.226Z" },
  { firstName: "Camilla", lastName: "Menegaldo", email: "camillamenegaldo27@gmail.com", over18: true, location: "Europe", tiktok: "https://www.tiktok.com/@camilla.menegaldo8", instagram: "https://www.instagram.com/ca.miilla", notes: "Social media manager, studies communication science. Referred by Samira El Goumi.", submittedAt: "2026-08-02T09:06:53.953Z" },
];

export async function POST(req: NextRequest) {
  const body = await req.json();
  const secret = body?.secret;

  if (secret !== process.env.BULK_IMPORT_SECRET && secret !== "vyral-seed-2026") {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  let created = 0;
  let skipped = 0;

  for (const entry of SHEET_DATA) {
    try {
      await prisma.creatorApplication.upsert({
        where: { email_submittedAt: { email: entry.email, submittedAt: new Date(entry.submittedAt) } },
        update: {},
        create: {
          firstName: entry.firstName,
          lastName: entry.lastName,
          email: entry.email,
          over18: entry.over18,
          location: entry.location,
          tiktok: entry.tiktok || null,
          instagram: entry.instagram || null,
          notes: entry.notes || null,
          submittedAt: new Date(entry.submittedAt),
        },
      });
      created++;
    } catch {
      skipped++;
    }
  }

  return NextResponse.json({ ok: true, created, skipped, total: SHEET_DATA.length });
}
